# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from scpedia_protos.pool.v1 import pool_pb2 as scpedia__protos_dot_pool_dot_v1_dot_pool__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in scpedia_protos/pool/v1/pool_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PoolServiceStub(object):
    """- INVALID_ARGUMENT: некорректные параметры
    - INTERNAL

    Сервис предоставляет доступ пулу загруженных статей
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetArticle = channel.unary_unary(
                '/scpedia.pool.v1.PoolService/GetArticle',
                request_serializer=scpedia__protos_dot_pool_dot_v1_dot_pool__pb2.GetArticleRequest.SerializeToString,
                response_deserializer=scpedia__protos_dot_pool_dot_v1_dot_pool__pb2.GetArticleResponse.FromString,
                _registered_method=True)


class PoolServiceServicer(object):
    """- INVALID_ARGUMENT: некорректные параметры
    - INTERNAL

    Сервис предоставляет доступ пулу загруженных статей
    """

    def GetArticle(self, request, context):
        """Возвращает статью из пула по вектору предпочтений пользователя.

        Ошибки: INVALID_ARGUMENT, INTERNAL
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PoolServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetArticle': grpc.unary_unary_rpc_method_handler(
                    servicer.GetArticle,
                    request_deserializer=scpedia__protos_dot_pool_dot_v1_dot_pool__pb2.GetArticleRequest.FromString,
                    response_serializer=scpedia__protos_dot_pool_dot_v1_dot_pool__pb2.GetArticleResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'scpedia.pool.v1.PoolService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('scpedia.pool.v1.PoolService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PoolService(object):
    """- INVALID_ARGUMENT: некорректные параметры
    - INTERNAL

    Сервис предоставляет доступ пулу загруженных статей
    """

    @staticmethod
    def GetArticle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scpedia.pool.v1.PoolService/GetArticle',
            scpedia__protos_dot_pool_dot_v1_dot_pool__pb2.GetArticleRequest.SerializeToString,
            scpedia__protos_dot_pool_dot_v1_dot_pool__pb2.GetArticleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
