# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: scpedia_protos/pool/v1/pool.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'scpedia_protos/pool/v1/pool.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!scpedia_protos/pool/v1/pool.proto\x12\x0fscpedia.pool.v1\"P\n\x0b\x41rticleMeta\x12\x0e\n\x06pageid\x18\x01 \x01(\x03\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0b\n\x03url\x18\x03 \x01(\t\x12\x15\n\rthumbnail_url\x18\x04 \x01(\t\"T\n\x07\x41rticle\x12*\n\x04meta\x18\x01 \x01(\x0b\x32\x1c.scpedia.pool.v1.ArticleMeta\x12\x0f\n\x07\x65xtract\x18\x02 \x01(\t\x12\x0c\n\x04lang\x18\x03 \x01(\t\"-\n\x10PreferenceVector\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x0b\n\x03\x64im\x18\x02 \x01(\r\"\x89\x01\n\x11GetArticleRequest\x12\x12\n\nmin_length\x18\x01 \x01(\x05\x12\x0c\n\x04text\x18\x02 \x01(\x08\x12\r\n\x05image\x18\x03 \x01(\x08\x12\x0c\n\x04lang\x18\x04 \x01(\t\x12\x35\n\npreference\x18\x05 \x01(\x0b\x32!.scpedia.pool.v1.PreferenceVector\"N\n\x12GetArticleResponse\x12)\n\x07\x61rticle\x18\x01 \x01(\x0b\x32\x18.scpedia.pool.v1.Article\x12\r\n\x05\x66ound\x18\x02 \x01(\x08\x32\x64\n\x0bPoolService\x12U\n\nGetArticle\x12\".scpedia.pool.v1.GetArticleRequest\x1a#.scpedia.pool.v1.GetArticleResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'scpedia_protos.pool.v1.pool_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ARTICLEMETA']._serialized_start=54
  _globals['_ARTICLEMETA']._serialized_end=134
  _globals['_ARTICLE']._serialized_start=136
  _globals['_ARTICLE']._serialized_end=220
  _globals['_PREFERENCEVECTOR']._serialized_start=222
  _globals['_PREFERENCEVECTOR']._serialized_end=267
  _globals['_GETARTICLEREQUEST']._serialized_start=270
  _globals['_GETARTICLEREQUEST']._serialized_end=407
  _globals['_GETARTICLERESPONSE']._serialized_start=409
  _globals['_GETARTICLERESPONSE']._serialized_end=487
  _globals['_POOLSERVICE']._serialized_start=489
  _globals['_POOLSERVICE']._serialized_end=589
# @@protoc_insertion_point(module_scope)
