# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: scpedia_protos/rec/v1/rec.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'scpedia_protos/rec/v1/rec.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fscpedia_protos/rec/v1/rec.proto\x12\x0escpedia.rec.v1\"k\n\x07\x41rticle\x12\x0e\n\x06pageid\x18\x01 \x01(\x03\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0b\n\x03url\x18\x03 \x01(\t\x12\x15\n\rthumbnail_url\x18\x04 \x01(\t\x12\x0f\n\x07\x65xtract\x18\x05 \x01(\t\x12\x0c\n\x04lang\x18\x06 \x01(\t\"q\n\x11GetArticleRequest\x12\x0e\n\x06userid\x18\x01 \x01(\x03\x12\r\n\x05\x63ount\x18\x02 \x01(\r\x12\x0c\n\x04lang\x18\x03 \x01(\t\x12\x12\n\nmin_length\x18\x04 \x01(\x05\x12\x0c\n\x04text\x18\x05 \x01(\x08\x12\r\n\x05image\x18\x06 \x01(\x08\"?\n\x12GetArticleResponse\x12)\n\x08\x61rticles\x18\x01 \x03(\x0b\x32\x17.scpedia.rec.v1.Article\"Y\n\x17UpdatePreferenceRequest\x12\x0e\n\x06userid\x18\x01 \x01(\x03\x12\x0c\n\x04lang\x18\x02 \x01(\t\x12\x0e\n\x06pageid\x18\x03 \x01(\x03\x12\x10\n\x08reaction\x18\x04 \x01(\x05\"+\n\x18UpdatePreferenceResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"=\n\x11UpsertUserRequest\x12\x0e\n\x06userid\x18\x01 \x01(\x03\x12\x18\n\x10\x63\x61libration_size\x18\x02 \x01(\x05\"%\n\x12\x43reateUserResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"$\n\x11ResetUserResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xf0\x02\n\nRecService\x12S\n\nGetArticle\x12!.scpedia.rec.v1.GetArticleRequest\x1a\".scpedia.rec.v1.GetArticleResponse\x12\x65\n\x10UpdatePreference\x12\'.scpedia.rec.v1.UpdatePreferenceRequest\x1a(.scpedia.rec.v1.UpdatePreferenceResponse\x12S\n\nCreateUser\x12!.scpedia.rec.v1.UpsertUserRequest\x1a\".scpedia.rec.v1.CreateUserResponse\x12Q\n\tResetUser\x12!.scpedia.rec.v1.UpsertUserRequest\x1a!.scpedia.rec.v1.ResetUserResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'scpedia_protos.rec.v1.rec_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ARTICLE']._serialized_start=51
  _globals['_ARTICLE']._serialized_end=158
  _globals['_GETARTICLEREQUEST']._serialized_start=160
  _globals['_GETARTICLEREQUEST']._serialized_end=273
  _globals['_GETARTICLERESPONSE']._serialized_start=275
  _globals['_GETARTICLERESPONSE']._serialized_end=338
  _globals['_UPDATEPREFERENCEREQUEST']._serialized_start=340
  _globals['_UPDATEPREFERENCEREQUEST']._serialized_end=429
  _globals['_UPDATEPREFERENCERESPONSE']._serialized_start=431
  _globals['_UPDATEPREFERENCERESPONSE']._serialized_end=474
  _globals['_UPSERTUSERREQUEST']._serialized_start=476
  _globals['_UPSERTUSERREQUEST']._serialized_end=537
  _globals['_CREATEUSERRESPONSE']._serialized_start=539
  _globals['_CREATEUSERRESPONSE']._serialized_end=576
  _globals['_RESETUSERRESPONSE']._serialized_start=578
  _globals['_RESETUSERRESPONSE']._serialized_end=614
  _globals['_RECSERVICE']._serialized_start=617
  _globals['_RECSERVICE']._serialized_end=985
# @@protoc_insertion_point(module_scope)
