# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from scpedia_protos.rec.v1 import rec_pb2 as scpedia__protos_dot_rec_dot_v1_dot_rec__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in scpedia_protos/rec/v1/rec_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RecServiceStub(object):
    """- INVALID_ARGUMENT: некорректные параметры
    - DEADLINE_EXCEEDED: не уложились в deadline клиента
    - INTERNAL

    Сервис предоставляет доступ пулу загруженных статей
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetArticle = channel.unary_unary(
                '/scpedia.rec.v1.RecService/GetArticle',
                request_serializer=scpedia__protos_dot_rec_dot_v1_dot_rec__pb2.GetArticleRequest.SerializeToString,
                response_deserializer=scpedia__protos_dot_rec_dot_v1_dot_rec__pb2.GetArticleResponse.FromString,
                _registered_method=True)
        self.UpdatePreference = channel.unary_unary(
                '/scpedia.rec.v1.RecService/UpdatePreference',
                request_serializer=scpedia__protos_dot_rec_dot_v1_dot_rec__pb2.UpdatePreferenceRequest.SerializeToString,
                response_deserializer=scpedia__protos_dot_rec_dot_v1_dot_rec__pb2.UpdatePreferenceResponse.FromString,
                _registered_method=True)
        self.CreateUser = channel.unary_unary(
                '/scpedia.rec.v1.RecService/CreateUser',
                request_serializer=scpedia__protos_dot_rec_dot_v1_dot_rec__pb2.UpsertUserRequest.SerializeToString,
                response_deserializer=scpedia__protos_dot_rec_dot_v1_dot_rec__pb2.CreateUserResponse.FromString,
                _registered_method=True)
        self.ResetUser = channel.unary_unary(
                '/scpedia.rec.v1.RecService/ResetUser',
                request_serializer=scpedia__protos_dot_rec_dot_v1_dot_rec__pb2.UpsertUserRequest.SerializeToString,
                response_deserializer=scpedia__protos_dot_rec_dot_v1_dot_rec__pb2.ResetUserResponse.FromString,
                _registered_method=True)


class RecServiceServicer(object):
    """- INVALID_ARGUMENT: некорректные параметры
    - DEADLINE_EXCEEDED: не уложились в deadline клиента
    - INTERNAL

    Сервис предоставляет доступ пулу загруженных статей
    """

    def GetArticle(self, request, context):
        """Возвращает статьи, рекомендованные для пользователя

        Ошибки: INVALID_ARGUMENT, DEADLINE_EXCEEDED, INTERNAL
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePreference(self, request, context):
        """Обновляет предпочтения по реакции на выбранную статью

        Ошибки: INVALID_ARGUMENT, DEADLINE_EXCEEDED, INTERNAL
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateUser(self, request, context):
        """Создаёт объект пользователя

        Ошибки: INVALID_ARGUMENT, DEADLINE_EXCEEDED, INTERNAL
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetUser(self, request, context):
        """Сбрасывает предпочтения для пользователя

        Ошибки: INVALID_ARGUMENT, DEADLINE_EXCEEDED, INTERNAL
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RecServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetArticle': grpc.unary_unary_rpc_method_handler(
                    servicer.GetArticle,
                    request_deserializer=scpedia__protos_dot_rec_dot_v1_dot_rec__pb2.GetArticleRequest.FromString,
                    response_serializer=scpedia__protos_dot_rec_dot_v1_dot_rec__pb2.GetArticleResponse.SerializeToString,
            ),
            'UpdatePreference': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePreference,
                    request_deserializer=scpedia__protos_dot_rec_dot_v1_dot_rec__pb2.UpdatePreferenceRequest.FromString,
                    response_serializer=scpedia__protos_dot_rec_dot_v1_dot_rec__pb2.UpdatePreferenceResponse.SerializeToString,
            ),
            'CreateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUser,
                    request_deserializer=scpedia__protos_dot_rec_dot_v1_dot_rec__pb2.UpsertUserRequest.FromString,
                    response_serializer=scpedia__protos_dot_rec_dot_v1_dot_rec__pb2.CreateUserResponse.SerializeToString,
            ),
            'ResetUser': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetUser,
                    request_deserializer=scpedia__protos_dot_rec_dot_v1_dot_rec__pb2.UpsertUserRequest.FromString,
                    response_serializer=scpedia__protos_dot_rec_dot_v1_dot_rec__pb2.ResetUserResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'scpedia.rec.v1.RecService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('scpedia.rec.v1.RecService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RecService(object):
    """- INVALID_ARGUMENT: некорректные параметры
    - DEADLINE_EXCEEDED: не уложились в deadline клиента
    - INTERNAL

    Сервис предоставляет доступ пулу загруженных статей
    """

    @staticmethod
    def GetArticle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scpedia.rec.v1.RecService/GetArticle',
            scpedia__protos_dot_rec_dot_v1_dot_rec__pb2.GetArticleRequest.SerializeToString,
            scpedia__protos_dot_rec_dot_v1_dot_rec__pb2.GetArticleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdatePreference(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scpedia.rec.v1.RecService/UpdatePreference',
            scpedia__protos_dot_rec_dot_v1_dot_rec__pb2.UpdatePreferenceRequest.SerializeToString,
            scpedia__protos_dot_rec_dot_v1_dot_rec__pb2.UpdatePreferenceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scpedia.rec.v1.RecService/CreateUser',
            scpedia__protos_dot_rec_dot_v1_dot_rec__pb2.UpsertUserRequest.SerializeToString,
            scpedia__protos_dot_rec_dot_v1_dot_rec__pb2.CreateUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResetUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scpedia.rec.v1.RecService/ResetUser',
            scpedia__protos_dot_rec_dot_v1_dot_rec__pb2.UpsertUserRequest.SerializeToString,
            scpedia__protos_dot_rec_dot_v1_dot_rec__pb2.ResetUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
