# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from scpedia_protos.wiki.v1 import wiki_pb2 as scpedia__protos_dot_wiki_dot_v1_dot_wiki__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in scpedia_protos/wiki/v1/wiki_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WikiServiceStub(object):
    """- INVALID_ARGUMENT: некорректные параметры
    - RESOURCE_EXHAUSTED: превышены лимиты
    - UNAVAILABLE: внешнее API недоступно / сетевые проблемы
    - DEADLINE_EXCEEDED: не уложились в deadline клиента
    - NOT_FOUND: объект не найден через внешнее API
    - INTERNAL

    Сервис предоставляет доступ к статьям из википедии, используя внешнее API
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetRandomArticle = channel.unary_unary(
                '/scpedia.wiki.v1.WikiService/GetRandomArticle',
                request_serializer=scpedia__protos_dot_wiki_dot_v1_dot_wiki__pb2.GetRandomArticleRequest.SerializeToString,
                response_deserializer=scpedia__protos_dot_wiki_dot_v1_dot_wiki__pb2.GetArticleResponse.FromString,
                _registered_method=True)
        self.GetArticleByTitle = channel.unary_unary(
                '/scpedia.wiki.v1.WikiService/GetArticleByTitle',
                request_serializer=scpedia__protos_dot_wiki_dot_v1_dot_wiki__pb2.GetArticleByTitleRequest.SerializeToString,
                response_deserializer=scpedia__protos_dot_wiki_dot_v1_dot_wiki__pb2.GetArticleResponse.FromString,
                _registered_method=True)
        self.GetArticleByPageId = channel.unary_unary(
                '/scpedia.wiki.v1.WikiService/GetArticleByPageId',
                request_serializer=scpedia__protos_dot_wiki_dot_v1_dot_wiki__pb2.GetArticleByPageIdRequest.SerializeToString,
                response_deserializer=scpedia__protos_dot_wiki_dot_v1_dot_wiki__pb2.GetArticleResponse.FromString,
                _registered_method=True)
        self.SearchArticles = channel.unary_unary(
                '/scpedia.wiki.v1.WikiService/SearchArticles',
                request_serializer=scpedia__protos_dot_wiki_dot_v1_dot_wiki__pb2.SearchArticlesRequest.SerializeToString,
                response_deserializer=scpedia__protos_dot_wiki_dot_v1_dot_wiki__pb2.SearchArticlesResponse.FromString,
                _registered_method=True)


class WikiServiceServicer(object):
    """- INVALID_ARGUMENT: некорректные параметры
    - RESOURCE_EXHAUSTED: превышены лимиты
    - UNAVAILABLE: внешнее API недоступно / сетевые проблемы
    - DEADLINE_EXCEEDED: не уложились в deadline клиента
    - NOT_FOUND: объект не найден через внешнее API
    - INTERNAL

    Сервис предоставляет доступ к статьям из википедии, используя внешнее API
    """

    def GetRandomArticle(self, request, context):
        """Возвращает случайную статью.

        Ошибки: INVALID_ARGUMENT, RESOURCE_EXHAUSTED, UNAVAILABLE, DEADLINE_EXCEEDED, INTERNAL
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetArticleByTitle(self, request, context):
        """Возвращает статью по её названию (требуется точное соответствие).

        Ошибки: INVALID_ARGUMENT, RESOURCE_EXHAUSTED, UNAVAILABLE, DEADLINE_EXCEEDED, NOT_FOUND, INTERNAL
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetArticleByPageId(self, request, context):
        """Возвращает статью по её ID.

        Ошибки: INVALID_ARGUMENT, RESOURCE_EXHAUSTED, UNAVAILABLE, DEADLINE_EXCEEDED, NOT_FOUND, INTERNAL
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchArticles(self, request, context):
        """Поиск статей по строке запроса и возвращает метаданные (title + pageid).

        Ошибки: INVALID_ARGUMENT, RESOURCE_EXHAUSTED, UNAVAILABLE, DEADLINE_EXCEEDED, INTERNAL
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WikiServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetRandomArticle': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRandomArticle,
                    request_deserializer=scpedia__protos_dot_wiki_dot_v1_dot_wiki__pb2.GetRandomArticleRequest.FromString,
                    response_serializer=scpedia__protos_dot_wiki_dot_v1_dot_wiki__pb2.GetArticleResponse.SerializeToString,
            ),
            'GetArticleByTitle': grpc.unary_unary_rpc_method_handler(
                    servicer.GetArticleByTitle,
                    request_deserializer=scpedia__protos_dot_wiki_dot_v1_dot_wiki__pb2.GetArticleByTitleRequest.FromString,
                    response_serializer=scpedia__protos_dot_wiki_dot_v1_dot_wiki__pb2.GetArticleResponse.SerializeToString,
            ),
            'GetArticleByPageId': grpc.unary_unary_rpc_method_handler(
                    servicer.GetArticleByPageId,
                    request_deserializer=scpedia__protos_dot_wiki_dot_v1_dot_wiki__pb2.GetArticleByPageIdRequest.FromString,
                    response_serializer=scpedia__protos_dot_wiki_dot_v1_dot_wiki__pb2.GetArticleResponse.SerializeToString,
            ),
            'SearchArticles': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchArticles,
                    request_deserializer=scpedia__protos_dot_wiki_dot_v1_dot_wiki__pb2.SearchArticlesRequest.FromString,
                    response_serializer=scpedia__protos_dot_wiki_dot_v1_dot_wiki__pb2.SearchArticlesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'scpedia.wiki.v1.WikiService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('scpedia.wiki.v1.WikiService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WikiService(object):
    """- INVALID_ARGUMENT: некорректные параметры
    - RESOURCE_EXHAUSTED: превышены лимиты
    - UNAVAILABLE: внешнее API недоступно / сетевые проблемы
    - DEADLINE_EXCEEDED: не уложились в deadline клиента
    - NOT_FOUND: объект не найден через внешнее API
    - INTERNAL

    Сервис предоставляет доступ к статьям из википедии, используя внешнее API
    """

    @staticmethod
    def GetRandomArticle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scpedia.wiki.v1.WikiService/GetRandomArticle',
            scpedia__protos_dot_wiki_dot_v1_dot_wiki__pb2.GetRandomArticleRequest.SerializeToString,
            scpedia__protos_dot_wiki_dot_v1_dot_wiki__pb2.GetArticleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetArticleByTitle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scpedia.wiki.v1.WikiService/GetArticleByTitle',
            scpedia__protos_dot_wiki_dot_v1_dot_wiki__pb2.GetArticleByTitleRequest.SerializeToString,
            scpedia__protos_dot_wiki_dot_v1_dot_wiki__pb2.GetArticleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetArticleByPageId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scpedia.wiki.v1.WikiService/GetArticleByPageId',
            scpedia__protos_dot_wiki_dot_v1_dot_wiki__pb2.GetArticleByPageIdRequest.SerializeToString,
            scpedia__protos_dot_wiki_dot_v1_dot_wiki__pb2.GetArticleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchArticles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scpedia.wiki.v1.WikiService/SearchArticles',
            scpedia__protos_dot_wiki_dot_v1_dot_wiki__pb2.SearchArticlesRequest.SerializeToString,
            scpedia__protos_dot_wiki_dot_v1_dot_wiki__pb2.SearchArticlesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
